#ifdef __cplusplus
extern "C" {
#endif

// declare Ruby registration method generated by SWIG in mprodigy_wrap.c
extern void Init_Mprodigy(void);

// this method executed once on start of program
void Init_Mprodigy_extension(void) {
	// execute initialization of Ruby registration (generated by SWIG)
	Init_Mprodigy();
}

#ifdef __cplusplus
} //extern "C"
#endif